# Generated by Django 4.1.1 on 2023-02-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('ProductTypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categories.categories'),
        ),
    ]
