# Generated by Django 4.1 on 2023-03-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_birthday_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image_tag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
