# Generated by Django 4.1.1 on 2023-02-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductTypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=300)),
                ('product_image_tag', models.CharField(blank=True, max_length=300, null=True)),
                ('brands', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('retailer', models.CharField(blank=True, max_length=300, null=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductTypes.producttypes')),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(blank=True, max_length=300, null=True)),
                ('hard_drive_size', models.CharField(blank=True, max_length=300, null=True)),
                ('ram', models.CharField(blank=True, max_length=300, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=300, null=True)),
                ('processor_brand', models.CharField(blank=True, max_length=300, null=True)),
                ('processor_type', models.CharField(blank=True, max_length=300, null=True)),
                ('laptop_computer_type', models.CharField(blank=True, max_length=300, null=True)),
                ('memory_capacity', models.CharField(blank=True, max_length=300, null=True)),
                ('wireless_capability', models.CharField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FreshFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_type', models.CharField(blank=True, max_length=300, null=True)),
                ('form', models.CharField(blank=True, max_length=300, null=True)),
                ('special_diet_needs', models.CharField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, max_length=300, null=True)),
                ('container', models.CharField(blank=True, max_length=300, null=True)),
                ('fruit_type', models.CharField(blank=True, max_length=300, null=True)),
                ('special_diet_needs', models.CharField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_condition', models.CharField(blank=True, max_length=300, null=True)),
                ('flavor', models.CharField(blank=True, max_length=300, null=True)),
                ('cookie_type', models.CharField(blank=True, max_length=300, null=True)),
                ('special_diet_needs', models.CharField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=300, null=True)),
                ('shape', models.CharField(blank=True, max_length=300, null=True)),
                ('material', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.CharField(blank=True, max_length=300, null=True)),
                ('finish', models.CharField(blank=True, max_length=300, null=True)),
                ('seating_capacity', models.CharField(blank=True, max_length=300, null=True)),
                ('features', models.CharField(blank=True, max_length=300, null=True)),
                ('frame_material', models.CharField(blank=True, max_length=300, null=True)),
                ('recommended_room', models.CharField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.productsmodel')),
            ],
        ),
    ]
