# Generated by Django 4.1.1 on 2023-02-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='brands',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='Products.brands'),
            preserve_default=False,
        ),
    ]
