# Generated by Django 4.1 on 2023-03-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_coffetables_id_alter_cookies_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='productsmodel',
            old_name='brands',
            new_name='brand',
        ),
    ]
