# Generated by Django 4.1 on 2023-03-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_rename_brands_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energydrinks',
            old_name='container',
            new_name='flavor',
        ),
        migrations.RemoveField(
            model_name='energydrinks',
            name='form',
        ),
        migrations.RemoveField(
            model_name='energydrinks',
            name='fruit_type',
        ),
    ]
