# Generated by Django 4.1 on 2023-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_productsmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='variations',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
