# Generated by Django 4.1 on 2023-03-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_remove_productvariants_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.values'),
            preserve_default=False,
        ),
    ]
