# Generated by Django 4.1 on 2023-03-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_userreviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='availability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='pack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='shipping_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
