# Generated by Django 4.1 on 2023-03-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_productsmodel_availability_productsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='created_at',
            new_name='date',
        ),
    ]
