# Generated by Django 4.1 on 2023-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_rename_created_at_productsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='total_images',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
