# Generated by Django 4.1 on 2023-04-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_productsmodel_total_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='generic_image_tag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
